from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from granian._granian import RSGIHeaders

__all__ = ("RSGIScope",)


class RSGIScope(Protocol):
    """Typed protocol for granian's RSGIHTTPScope (no stub shipped)."""

    @property
    def proto(self) -> str: ...
    @property
    def rsgi_version(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query_string(self) -> str: ...
    @property
    def headers(self) -> "RSGIHeaders": ...
    @property
    def scheme(self) -> str: ...
    @property
    def http_version(self) -> str: ...
    @property
    def server(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def client(self) -> str: ...
